import = [
     "~/.config/alacritty/themes/catppuccin-mocha.toml"
	# "~/.config/alacritty/themes/catppuccin-frappe.toml"
	# "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    # "~/.config/alacritty/themes/gruvbox-dark.toml"
	# "~/.config/alacritty/themes/solarized-dark.toml"
    # "~/.config/alacritty/themes/onedark.toml"
] 

[env]
term = "xterm-256color"

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
opacity = 0.95
blur = true

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 3

[mouse]
hide_when_typing = true

